kind: pipeline
type: kubernetes
name: default

platform:
  arch: arm

steps:
- name: publish
  image:  plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: scrot/build-your-own-radar
    tags:
      - latest
      - '1.0'