kind: pipeline
type: kubernetes
name: default

platform:
  arch: arm

steps:
- name: publish
  image:  plugins/docker
  settings:
    username: dockerhub_username
    password: dockerhub_password
    repo: scrot/byor
    tags:
      - latest
      - '1.0'